## 10.2 커스텀 에러와 확장

에러 클래스를 직접 만들수 있다.

에러 클래스를 만들때는 `message`이나 `name`, 가능하다면 `stack` 프로퍼티를 지원해야 한다. 물론 이런 프로퍼티 이외에도 다른 프로퍼티를 지원할 수 있다.

에러 클래스를 만들때는 `Error` 를 상속하여 정의한다면  `obj instanceof Error`를 사용해서 에러 객체를 식별할 수 있다는 장점이 있다.

물론 `Error` 를 상속하지 않고 처음부터 만들어도 된다.



### 활용 예제 - ValidationError이라는 커스텀 에러 만들어서 활용하기

```js
class ReadError extends Error { // 데이터 읽기’와 같은 포괄적인 에러를 대변하기 위한 에러
  constructor(message, cause) {
    super(message);
    this.cause = cause;
    this.name = 'ReadError';
  }
}

class ValidationError extends Error { // 단순하게 검사용도의 에러
  constructor(message) {
    super(message);
    this.name = this.constructor.name; // ValidationError
  }
}

class PropertyRequiredError extends ValidationError { // 좀 더 구체적인 에러
  constructor(property) {
    super('No property: ' + property);
    this.name = this.constructor.name; // PropertyRequiredError
    this.property = property; // 어떤 프로퍼티가 누락이 되었는지 확인하는 용도!
  }
}

function validateUser(user) {
  if (!user.age) {
    throw new PropertyRequiredError('age');
  }

  if (!user.name) {
    throw new PropertyRequiredError('name');
  }
}

function readUser(json) {
  let user;

  try {
    user = JSON.parse(json);
  } catch (err) {
    if (err instanceof SyntaxError) {
      throw new ReadError('Syntax Error', err);
    } else {
      throw err;
    }
  }

  try {
    validateUser(user);
  } catch (err) {
    if (err instanceof ValidationError) {
      throw new ReadError('Validation Error', err);
    } else {
      throw err;
    }
  }
}

try {
  readUser('{잘못된 형식의 json}');
} catch (e) {
  if (e instanceof ReadError) {
    alert(e);
    // Original error: SyntaxError: Unexpected token b in JSON at position 1
    alert('Original error: ' + e.cause);
  } else {
    throw e;
  }
}

```

'예외 감싸기(wrapping exception)'라고 부른다. 예외 감싸기는 다음과 같은 순서로 진행된다.

1. '데이터 읽기’와 같은 포괄적인 에러를 대변하는 새로운 클래스 `ReadError`를 만든다.
2. 함수 `readUser` 발생한 `ValidationError`, `SyntaxError` 등의 에러는 `readUser` 내부에서 잡고 이때 `ReadError`를 생성한다.

이렇게 예외 감싸기 기술을 써 스키마를 변경하면 `readUser`를 호출하는 코드에선 계속해서 추가되는 예외처리를 분기문을 처리하지 않고 `ReadError`만 확인하면 된다.